function PAndT() {
    return (
        <div className="container nicelyDone">
            <div className="nicelyOne">
                <h5 className="d-flex justify-content-center ff-secondary text-center text-primary fw-normal">Privacy Policy || Terms & Condition</h5>
                <p>Effective Date: May 2022<br />Carriage Restaurant ("us", "we", or "our") operates the www.carriagehousemackinac.com website (the "Service").</p>
                <p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>
                <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from www.carriagehousemackinac.com</p>
            </div>
            <h4>DEFINITIONS</h4>
            <h6>PERSONAL DATA</h6>
            <p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
            <h6>USAGE DATA</h6>
            <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
            <h6>COOKIES</h6>
            <p>Cookies are small pieces of data stored on a User's device.</p>
            <h6>DATA CONTROLLER</h6>
            <p>Data Controller means a person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed.<br />For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
            <h6>DATA PROCESSOR (OR SERVICE PROVIDERS)</h6>
            <p>Data Processor (or Service Provider) means any person (other than an employee of the Data Controller) who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>
            <h6>DATA SUBJECT</h6>
            <p>Data Subject is any living individual who is the subject of Personal Data.</p>
            <h6>USER</h6>
            <p>The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
            <h6>INFORMATION COLLECTION AND USE</h6>
            <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
            <h6>CONTACT US</h6>
            <p>If you have any questions about this Privacy Policy, please contact us:</p>
            <ul>
                <li>By email: FreeFire@SDTHT.com</li>
                <li>By phone number: +012 345 67890</li>
            </ul>
        </div>
    );
}
export default PAndT;